---
#
# install grafana
#
- name: install yum repository
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - grafana.repo
  tags: grafana

- name: install rpm gpg key
  rpm_key: state=present key=https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana

- name: install grafana
  yum: name=grafana
  tags: grafana

#
# configure https
#
- include: self_signed_cert.yml
  tags: grafana

- name: rewrite grafana.ini
  lineinfile:
    dest: "{{ grafana_conf }}"
    regexp: "^{{ item.key }} "
    insertafter: "^;{{ item.key }} "
    line: "{{ item.key }} = {{ item.value }}"
    backup: yes
  with_items:
    - { key: "protocol", value: "https" }
    - { key: "cert_file", value: "{{ cert_path }}" }
    - { key: "cert_key", value: "{{ key_path }}" }
  tags: grafana

#
# start service
#
- name: start grafana-server
  service: name=grafana-server state=started
  tags: grafana

