---
- name: make script directory
  file: path={{ script_dir }} state=directory owner={{ user }} group={{ user }} mode=0755
  tags: cloudwatch-dump

- name: check if cloudwatch-dump is installed
  command: pip show {{ package_name }}
  ignore_errors: True
  changed_when: False
  failed_when: False
  register: check_installed
  tags: cloudwatch-dump

- name: install cloudwatch-dump package
  pip: name={{ item }} state=present
  with_items: package_url
  when: check_installed.stdout == ''
  tags: cloudwatch-dump

- name: fetch EC2 metadata
  ec2_facts:
  tags: cloudwatch-dump

- name: copy launcher script
  template: src={{ item }}.j2 dest={{ script_dir }}/{{ item }} mode=0755
  with_items:
    - cloudwatch_to_graphite.sh
  tags: cloudwatch-dump

- name: set cron
  cron: user={{ user }}
        state=present
        name="CloudWatch dumper script"
        minute="{{ cron.minute }}"
        hour="{{ cron.hour }}"
        job="{{ cron.job }}"
  tags: cloudwatch-dump
